:toc: macro
toc::[]

:doctype: book
:reproducible:
:source-highlighter: rouge
:listing-caption: Listing

== OASP4JS

[_OASP4JS_] is the OASP front-end implementation based on Angular framework. It supports the development of Angular applications.  https://github.com/oasp/oasp4Js[_OASP4JS_] includes Google Material Design as a main visual language, to take the maximum advantage of Angular possibilities and Material components. This makes it possible to build a modular, well-designed and responsive front-end applications.

=== OASP4JS Technology Stack

OASP4JS works on the top of Angular but also, it provides several tools, libraries and code conventions to make your Angular apps easier to develop based on the following technologies:

- http://angular.io/[Angular Framework] as the main development framework.

- https://github.com/angular/material2[Google Material2] as visual language and components.

- https://github.com/Teradata/covalent[Covalent Teradata] as Component and utilities library working with Google Material.

- https://yarnpkg.com/en/[Yarn] as a Project dependencies management tool.

The main advantages of these technologies are:

- Teradata provides:
* 4 available layouts that fits nowadays design necessities.
* Several tools and utilities regarding style conventions such as text size, padding, margins...
* Complex components as: Data tables, Chips with autocomplete, pagination...
- Google Material component library is composed by a number of fancy components like tabs, cards, buttons...
- Yarn is quite faster than NPM and provides some more functionalities to manage dependencies.

=== OASP4JS Tools

==== IDE
There is no integrated IDE with the framework. Therefore, you are free to use any IDE that fits your needs. Even though, we recommend the use of https://code.visualstudio.com/[Visual Studio Code], along with a https://github.com/oasp/oasp-vscode-ide[Guide of the most interesting plugins] to make your development even easier, with Typescript and Angular.

==== Angular/Cli
This https://github.com/angular/angular-cli[Angular CLI] helps the developer to automatize some common processes. It comes with https://github.com/webpack/webpack[Webpack] as a main bundler. It is widely used in the Angular community, thanks to the boost of the productivity that it provides at the time of creating new projects from scratch, serving and testing the project, creating new components, services, directives...

==== Testing
Testing helps the developers to be sure that all the typescripts in services and components are working properly. Moreover, it can also tests the HTML tags and properties. There are many options to test an Angular app, the default option is https://github.com/karma-runner/karma[Karma] and https://github.com/jasmine/jasmine[Jasmine].