:toc: macro
toc::[]

:doctype: book
:reproducible:
:source-highlighter: rouge
:listing-caption: Listing

== Steps to use Devon distribution in Linux OS

*  Navigate to devon dist folder and open a terminal.
* On the terminal, execute env.sh script, using [.].
  *[.]* is a command in linux shell ,
    it sources a script ,
    so it is included into your current shell environment.


[source,console]
----
. env.sh
----

* Executing of this script, guarantees that all environment variables like JAVA_HOME, M2_HOME are set.

* Once above steps are done, run create-or-update-workspace script, which inturn creates scripts for eclipse like eclipse-main.
And then , you can have things or steps which you want.
Above steps are necessary for Linux distribution, so that all environment variables are set.
For more details on devon distro in general, refer https://github.com/devonfw/devon-guide/wiki/getting-started-distribution-structure[here].

* For installing @angular/cli, run install-angular.sh script. This script requires you to enter root password and it will responsible to install node,
npm and angular. After script executes, test it using `$ node -v` and `$ npm -v` command.

* For installing sencha, run install-sencha.sh script. After script successfully executes you can test it with `sencha` command.





