
:doctype: book
:reproducible:
:source-highlighter: rouge
:listing-caption: Listing

== Devonfw Outline

=== Why do we use an open source core

In some countries of the SBU clients only accept open source stacks (most to mention customers who want to stay vendor-independent by principle), so being open is a market need. This also is the rationale for providing a open source reference architecture for the client built with AngularJs (open source itself).

=== Devonfw and Open Source

The Devonfw consist of OASP (Open Application Standard Platform) which started as an initiative of the German BU (Apps evolve). This project offers both a server side solution (based on Spring) and an AngularJS solution for client side.

Having an Open Source foundation is an advantage on clients that don’t want to be tied to an internal framework of a company like Capgemini. Since all the code is provided, the client is free to evolve it freely.

OASP itself is based on other established Open Source framework such as Spring, CXF or Hibernate. Adopting best practices and being enriched by the experience of our community of experts.

=== Contributing to Devonfw

Devonfw Platform is organized in a way that it is easy for you to contribute. Therefore, we have chosen to use _github_ (the number one platform for social coding) which provides lean processes and great tooling. Currently, most repositories are marked as private, hence invisible to you. You can send an email from your Capgemini account with your _github_ login to the devonfw team if you want to get access. Please ensure your real name is set in your _github_ account or your login is matching your Capgemini CORP login. You will be also added to our Capgemini OASP mailing list (see contact).

In order to contribute code, we use _git_ and _github_ _pull-requests_. Lead developers can directly commit to the git repository while (later) everybody can clone and fork the repository and create _pull-requests_. These can be reviewed, commented and discussed and finally integrated (or rejected).

We are very happy to receive contributions from projects or individual experts. Before you invest your time and work into a larger change or contribution, please get in contact before, to ensure that you will not waste your energy (somebody else might already work on the same thing, etc.). To get in touch and discuss with us please meet us on _Yammer_.