:toc: macro
toc::[]

:doctype: book
:reproducible:
:source-highlighter: rouge
:listing-caption: Listing

== Adapters

OASP4Fn provides some adapters to use the cloud services supported by the framework.

=== Types of adapters

The adapters are grouped depending in which kind of service is adapted. In this chapter we gonna describe and explain the different kinds of adapters the framework provides, an list the adapters of each type.

==== Data Base adapters

This type of adapter will let the user connect to a data base service, retrieve items, delete and insert them.
See link:++https://htmlpreview.github.io/?https://raw.githubusercontent.com/oasp/oasp4fn/master/doc/interfaces/_index_d_.fndbservice.html++[Interface FnDBService].

* List of data base adapters:
** *dynamo*:
- name: fn-dynamo
- import: `import dynamo from '@oasp/oasp4fn/dist/adapters/fn-dynamo'`

==== Storage adapters

This type of adapter will let the user connect to a storage service, download objects and delete them as binary data.
See link:++https://htmlpreview.github.io/?https://raw.githubusercontent.com/oasp/oasp4fn/master/doc/interfaces/_index_d_.fnstorageservice.html++[Interface FnStorageService].

* List of storage adapters:
** *s3*:
- name: fn-s3
- import: `import s3 from '@oasp/oasp4fn/dist/adapters/fn-s3'`

==== Authorization adapters

This type of adapter will let the user connect to a authorization service to retrieve the corresponding tokens of a user.
See link:++https://htmlpreview.github.io/?https://raw.githubusercontent.com/oasp/oasp4fn/master/doc/interfaces/_index_d_.fnauthservice.html++[Interface FnAuthService]

* List of data base adapters:
** *cognito*:
- name: fn-cognito
- import: `import cognito from '@oasp/oasp4fn/dist/adapters/fn-cognito'`