:toc: macro
toc::[]

:doctype: book
:reproducible:
:source-highlighter: rouge
:listing-caption: Listing

== Application Configuration

Furthermore of the specified before, in the file **oasp4fn.config.js**, it is specified the configuration of the events, deployment information and the runtime environment in which the handlers will run.

=== File structure

The file will contain an javascript exported object, which will contain specific properties of the future generated _serverless.yml_:

[source, javascript]
----
module.exports = {
   // Serverless properties 
}
----

There you can insert the properties in a json style format. You can check all the applicable properties at the https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/[official reference] , all of those can be defined normally except in two special cases:

* Provider property:

Inside this property are specified the provider and all the relative properties of the associated service which is going to run the functions, but you can only provide the name of the provider, and all the default properties will be added by OASP4Fn in the final _serverless.yml_:

[source, javascript]
----
module.exports = {
    provider: "google"
}
----

* Functions property: 

This property doesn't have to appear in the configuration file, because this property is extracted from the project structure and generated by OASP4Fn, but there is a possibility to specify a generic configuration of the events that our project has adding a property _events_, that will contain the configuration to each event:

[source, javascript]
----
module.exports = {
    events: { 
    http: { integration: 'lambda', cors: true, authorizer: {arn: 'arn:aws:cognito-idp:us-west-2:836886498299:userpool/us-west-2_1511o0vuo', claims: ['username']} }, 
    s3 : { bucket: 'conveyor-sls' }}
}
----

[IMPORTANT]
====
Keep in mind that all the properties specified in the configuration file will overwrite the default configuration property (if any), and not merge it, so if you want to add an property to the default package you have to add it rewriting the defaults ones (as can be appreciated in the http event above).
====

=== Handler configuration

In the last section we learned how to add the general configuration of our service, but what we do, in the case that we want to add or modify a single property in a handler? (the path of an http endpoint, for example), then we want to add it accros the _config_ property of OASP4Fn:

[source, typescript]
----
oasp4fn.config({path: 'attachments/{id}'});
----

That method acts as a dummy function, and should be situated just above the handler function. It will add properties to the handler event property, or delete the default ones or the specified in the _oasp4fn.config.js_ using the [source, typescript]undefined keyword:

[source, typescript]
----
oasp4fn.config({ path: 'login', authorizer: undefined });
----

=== Default configuration

In this section we're going to specify the default configuration that OASP4Fn for the different supported providers, which no one is specified, the default used will be the AWS provider.

==== AWS
 * provider:
    - name: 'aws'
    - runtime: 'node6.10'
    - region: 'us-west-2'
 * plugins:
    - 'serverless-webpack' 
    - 'serverless-offline'
 * events:
    - http:
        - integration: lambda
        - cors: true
        - method: <folder name>
    - s3:
        - created: 's3:ObjectCreated:*' / removed: 's3:ObjectRemoved:*' (depending on the folder name)
    - sns:
        - topicName: <folder name>
    - alexaskill:
        - <folder name>
    - stream: 
        - type: <folder name>
 * iamRoleStatements:
    - Effect: 'Allow', Action: [ 'dynamodb:*' ], Resource: 'arn:aws:dynamodb:*:*:*' 
    - Effect: 'Allow', Action: [ 's3:*' ], Resource: '*'

[IMPORTANT]
====
The _iamRoleStatements_ property in the _serverless.yml_ is inside the provider property, but must be declared outside it in the configuration file in order to change it, this is made for avoid the possibility of have to change all the provider properties if you want to change some of the _iamRoleStatements_.
====
